### ISSUE TITLE
DSM Lab PDF display issue

### ISSUE THREAD

**Issue by gnaneswar-k** [IIITH-Resources/Digital_System-Microcontrollers#1]
Upon clicking the name of the pdf, the document viewer opens next to the Lab 7 button. Probably a break line is missing.

1. Go to DSM Labs
2. Click on any of the pdfs
3. See error

Screenshots
![image](https://user-images.githubusercontent.com/97674245/151405740-399a6621-fdec-493a-900d-ba33486cefd1.png)

Laptop:
 - OS: Windows 10 21H2 (OS Build 19044.1415)
 - Browser Microsoft Edge Version 97.0.1072.55 (Official build) (64-bit)

**Comment by ghost** [comment]
I have added the missing closing tags which might be causing the problem. Instead of ending the comment using ‘- ->’ someone had used ‘->’.

**Comment by ghost** [comment]
Kindly check back after 5 minutes.

**Comment by ghost** [comment]
While testing the website I have confirmed that the issue has been fixed and hence I’m closing this issue. If the issue still persists at your side please feel free to reopen this issue.
